In [1]:
#contains a function to plot stuff
import matplotlib.pyplot as plt

def plot(x, y, xlabel, ylabel, title):
    plt.plot(x, y)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.show()

In [6]:
#uses pandas to open a file
import pandas as pd

def openCSVFile(inputFilePath):
    data = pd.read_csv(inputFilePath, engine="python", sep="\n", header=None)
    data = data[0].str.split(";", expand=True)
    
    return data

In [7]:
data = openCSVFile("Data/training_files/training_files/chan1/background_chan1_7.79.csv")

data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,7051621,z_jets,1,390017,0.538031,"j,407492,393095,-0.266637,-2.68505","j,633731,283693,1.4419,-0.451286","j,269569,145318,1.22541,2.36482","j,138520,110826,0.688498,2.66743","j,101435,87189.8,0.563578,-2.49198","j,183193,38577.6,-2.23818,-0.295831",,None,None,None,None,None,None,None,None
1,33064349,njets,1,217448,0.663545,"j,707690,390901,1.19577,-2.48665","j,165970,162374,-0.073124,0.558267","j,213806,88382.7,1.52776,0.769609","j,190327,63638.8,-1.75736,-1.3494","j,324303,56631.5,2.42978,3.03834",,None,None,None,None,None,None,None,None,None
2,179392659,njets,1,220238,-1.45891,"j,484710,388499,0.669438,2.1595","j,466224,209644,1.43709,-1.48085","j,173345,159358,0.3921,0.722837","b,76508.9,63430.3,0.614221,-0.229462",,None,None,None,None,None,None,None,None,None,None
3,185746896,njets,1,237999,1.30691,"j,913056,245434,-1.98767,0.978061","j,228497,202999,0.478876,-2.01883","j,153458,146721,-0.259158,-1.87386","j,126963,126389,0.0382953,-2.45528","j,50958.8,41187,0.653297,2.54775",,None,None,None,None,None,None,None,None,None
4,84616096,njets,1,229855,-0.953545,"j,302325,294936,0.181659,3.03634","j,360228,251837,-0.8903,0.173217","j,203074,200825,0.149532,2.22357","j,359058,56262.1,2.54026,-0.807584",,None,None,None,None,None,None,None,None,None,None

In [8]:
print(data[1][0])

z_jets

In [74]:
class Particle:
    def __init__(self, obj, E, pt, eta, phi):
        self.obj=obj
        self.E=E
        self.pt=pt
        self.eta=eta
        self.phi=phi
    def __init__(self, particleValues):
        self.obj=particleValues[0]
        self.E= particleValues[1]
        self.pt= particleValues[2]
        self.eta= particleValues[3]
        self.phi= particleValues[4]

In [113]:
#Plot multiplicity: number of jets, number of leptons, number of muons use density option in matplotlib density=1

In [176]:
def makeDataList(data):
    dimensions=data.shape
    ymax= dimensions[0]
    xmax= dimensions[1]
    dataList= []
    
    for y in range(0, ymax):
        row = data.iloc[y:y+1]
        eventID = int(row[0])
        processID = row[1]
        eventWeight = float(row[2])
        MET = float(row[3])
        METPhi = float(row[4])
        
        particleList=[]
        
        for x in range(5, xmax):
            particleValues= row[x].str.split(",")[y]
            if particleValues is not None:
                if len(particleValues)==5:
                    obj = particleValues[0]
                    E = particleValues[1]
                    pt = particleValues[2]
                    eta = particleValues[3]
                    phi = particleValues[4]
                
                    particle = Particle(obj, E, pt, eta, phi)
                    particleList.append(particle)
        
        eventDict = {
            "eventID" : eventID,
            "processID" : processID,
            "eventWeight" : eventWeight,
            "MET" : MET,
            "METPhi" : METPhi,
            "particleList" : particleList
        }
        
        dataList.append(eventDict)
    return dataList

In [ ]:
dataList = makeDataList(data)

In [175]:
print(dataList[0])
print(dataList[0]["particleList"][0].phi)

{'eventID': 7051621, 'processID': 0    z_jets
Name: 1, dtype: object, 'eventWeight': 1.0, 'MET': 390017.0, 'METPhi': 0.538031, 'particleList': [<__main__.Particle object at 0x0000022E2C615FA0>, <__main__.Particle object at 0x0000022E2C615FD0>, <__main__.Particle object at 0x0000022E2C601430>, <__main__.Particle object at 0x0000022E2C5FB700>, <__main__.Particle object at 0x0000022E2C5C5C40>, <__main__.Particle object at 0x0000022E2C5AA9A0>]}
-2.68505